title: GoogleAPI
author: SOTR654
url: https://sotr654.github.io/copy/
description: Google services in Roblox!

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: SOTR654
    card: summary_large_image

theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in page layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  
  #show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  
  # following keys are using to create home layout
  show_tags: true # show tags in a blog posts

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
