title: GoogleAPI
author: SOTR654
description: Google services in Roblox!
url: https://sotr654.github.io/copy/

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: SOTR654
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  #appearance_toggle: true # if appearance can be switched by user
  date_format: "%Y-%m-%d" # customize how date is formatted
  
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  
highlighter: rouge

sass:
  style: :compressed

plugins_dir: _plugins

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
